platform :ios, '10.0'
target 'FilmSquad' do

pod 'BmobSDK'
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod 'EaseMobSDK', :git => 'https://github.com/easemob/sdk-ios-cocoapods.git'
pod 'SVPullToRefresh'
pod 'LMSideBarController'
pod 'Masonry'
pod 'JSONModel'
pod 'YYText'
pod 'SVProgressHUD'

end
